import { componentsReducer, propsReducer } from '../../utils'

export function nuxtui2() {
  const map: any = [

  ]

  return propsReducer(map)
}

export function nuxtui2Components() {
  const map = [
    [
      'Accordion',
      'Accordion',
      '<Accordion></Accordion>',
    ],
    [
      'AccordionItem',
      'AccordionItem',
      '<AccordionItem></AccordionItem>',
    ],
    [
      'Avatar',
      'Avatar',
      '<Avatar></Avatar>',
    ],
    [
      'AvatarGroup',
      'AvatarGroup',
      '<AvatarGroup></AvatarGroup>',
    ],
    [
      'Badge',
      'Badge',
      '<Badge></Badge>',
    ],
    [
      'Button',
      'Button',
      '<Button></Button>',
    ],
    [
      'ButtonGroup',
      'ButtonGroup',
      '<ButtonGroup></ButtonGroup>',
    ],
    [
      'Card',
      'Card',
      '<Card></Card>',
    ],
    [
      'Checkbox',
      'Checkbox',
      '<Checkbox></Checkbox>',
    ],
    [
      'CheckboxGroup',
      'CheckboxGroup',
      '<CheckboxGroup></CheckboxGroup>',
    ],
    [
      'Chip',
      'Chip',
      '<Chip></Chip>',
    ],
    [
      'CircularProgress',
      'CircularProgress',
      '<CircularProgress></CircularProgress>',
    ],
    [
      'Code',
      'Code',
      '<Code></Code>',
    ],
    [
      'Divider',
      'Divider',
      '<Divider></Divider>',
    ],
    [
      'Dropdown',
      'Dropdown',
      '<Dropdown></Dropdown>',
    ],
    [
      'DropdownItem',
      'DropdownItem',
      '<DropdownItem></DropdownItem>',
    ],
    [
      'DropdownMenu',
      'DropdownMenu',
      '<DropdownMenu></DropdownMenu>',
    ],
    [
      'DropdownSection',
      'DropdownSection',
      '<DropdownSection></DropdownSection>',
    ],
    [
      'DropdownTrigger',
      'DropdownTrigger',
      '<DropdownTrigger></DropdownTrigger>',
    ],
    [
      'Image',
      'Image',
      '<Image></Image>',
    ],
    [
      'Input',
      'Input',
      '<Input></Input>',
    ],
    [
      'KeyboardKey',
      'KeyboardKey',
      '<KeyboardKey></KeyboardKey>',
    ],
    [
      'Link',
      'Link',
      '<Link></Link>',
    ],
    [
      'Listbox',
      'Listbox',
      '<Listbox></Listbox>',
    ],
    [
      'ListboxItem',
      'ListboxItem',
      '<ListboxItem></ListboxItem>',
    ],
    [
      'ListboxSection',
      'ListboxSection',
      '<ListboxSection></ListboxSection>',
    ],
    [
      'Modal',
      'Modal',
      '<Modal></Modal>',
    ],
    [
      'Navbar',
      'Navbar',
      '<Navbar></Navbar>',
    ],
    [
      'NavbarContent',
      'NavbarContent',
      '<NavbarContent></NavbarContent>',
    ],
    [
      'NavbarItem',
      'NavbarItem',
      '<NavbarItem></NavbarItem>',
    ],
    [
      'NavbarMenu',
      'NavbarMenu',
      '<NavbarMenu></NavbarMenu>',
    ],
    [
      'NavbarMenuToggle',
      'NavbarMenuToggle',
      '<NavbarMenuToggle></NavbarMenuToggle>',
    ],
    [
      'Pagination',
      'Pagination',
      '<Pagination></Pagination>',
    ],
    [
      'Popover',
      'Popover',
      '<Popover></Popover>',
    ],
    [
      'PopoverContent',
      'PopoverContent',
      '<PopoverContent></PopoverContent>',
    ],
    [
      'PopoverTrigger',
      'PopoverTrigger',
      '<PopoverTrigger></PopoverTrigger>',
    ],
    [
      'Radio',
      'Radio',
      '<Radio></Radio>',
    ],
    [
      'RadioGroup',
      'RadioGroup',
      '<RadioGroup></RadioGroup>',
    ],
    [
      'Select',
      'Select',
      '<Select></Select>',
    ],
    [
      'ShadowScroll',
      'ShadowScroll',
      '<ShadowScroll></ShadowScroll>',
    ],
    [
      'Skeleton',
      'Skeleton',
      '<Skeleton></Skeleton>',
    ],
    [
      'Snippet',
      'Snippet',
      '<Snippet></Snippet>',
    ],
    [
      'Spacer',
      'Spacer',
      '<Spacer></Spacer>',
    ],
    [
      'Switch',
      'Switch',
      '<Switch></Switch>',
    ],
    [
      'Tab',
      'Tab',
      '<Tab></Tab>',
    ],
    [
      'Table',
      'Table',
      '<Table></Table>',
    ],
    [
      'TableBody',
      'TableBody',
      '<TableBody></TableBody>',
    ],
    [
      'TableCell',
      'TableCell',
      '<TableCell></TableCell>',
    ],
    [
      'TableColumn',
      'TableColumn',
      '<TableColumn></TableColumn>',
    ],
    [
      'TableHeader',
      'TableHeader',
      '<TableHeader></TableHeader>',
    ],
    [
      'TableRow',
      'TableRow',
      '<TableRow></TableRow>',
    ],
    [
      'Tabs',
      'Tabs',
      '<Tabs></Tabs>',
    ],
    [
      'Textarea',
      'Textarea',
      '<Textarea></Textarea>',
    ],
    [
      'Tooltip',
      'Tooltip',
      '<Tooltip></Tooltip>',
    ],
    [
      'User',
      'User',
      '<User></User>',
    ],
  ]
  return componentsReducer(map)
}
