import { componentsReducer, propsReducer } from '../../utils'
import ElRow from './row.json'
import ElCol from './col.json'
import ElAlert from './alert.json'
import ElButton from './button.json'
import ElContainer from './container.json'
import ElHeader from './header.json'
import ElAside from './aside.json'
import ElFooter from './footer.json'
import ElLink from './link.json'
import ElRadio from './radio.json'
import ElRadioGroup from './radioGroup.json'
import ElRadioButton from './radioButton.json'
import ElForm from './form.json'
import ElFormItem from './formItem.json'
import ElTable from './table.json'
import ElTableColumn from './tableColumn.json'
import ElCard from './card.json'
import ElInput from './input.json'
import ElAutocomplete from './autocomplete.json'
import ElSelect from './select.json'
import ElCascader from './cascader.json'
import ElCascaderPanel from './cascaderPanel.json'
import ElCheckbox from './checkbox.json'
import ElCheckboxGroup from './checkboxGroup.json'
import ElCheckboxButton from './checkboxButton.json'
import ElBadge from './badge.json'
import ElBreadcrumb from './breadcrumb.json'
import ElCarousel from './carousel.json'
import ElCarouselItem from './carouselItem.json'
import ElCollapse from './collapse.json'
import ElCollapseItem from './collapseItem.json'
import ElColorPicker from './colorPicker.json'
import ElImage from './image.json'
import ElEmpty from './empty.json'
import ElDropdown from './dropdown.json'
import ElDropdownMenuItem from './dropdownMenuItem.json'
import ElDrawer from './drawer.json'
import ElDivider from './divider.json'
import ElDialog from './dialog.json'
import ElDescriptions from './descriptions.json'
import ElDatepicker from './datePicker.json'
import ElDatetimePicker from './datetimePicker.json'
import ElMenu from './menu.json'
import ElMenuItem from './menuItem.json'
import ElPageHeader from './pageHeader.json'
import ElPagination from './pagination.json'
import ElPopconfirm from './popconfirm.json'
import ElPopover from './popover.json'
import ElProgress from './progress.json'
import ElRate from './rate.json'
import ElResult from './result.json'
import ElSkeleton from './skeleton.json'
import ElSkeletonItem from './skeletonItem.json'
import ElSlider from './slider.json'
import ElStatistic from './statistic.json'
import ElStep from './step.json'
import ElSteps from './steps.json'
import ElSubmenu from './submenu.json'
import ElSwitch from './switch.json'
import ElTabPane from './tabPane.json'
import ElTabs from './tabs.json'
import ElTag from './tag.json'
import ElTimeline from './timeline.json'
import ElTimelineItem from './timelineItem.json'
import ElTimePicker from './timePicker.json'
import ElTimeSelect from './timeSelect.json'
import ElTooltip from './tooltip.json'
import ElTransfer from './transfer.json'
import ElTree from './tree.json'
import ElUpload from './upload.json'
import ElAvatar from './avatar.json'
import ElBacktop from './backtop.json'

export function elementUi2(extensionContext: any) {
  const map: any = [
    ElRow,
    ElCol,
    ElAlert,
    ElButton,
    ElContainer,
    ElHeader,
    ElAside,
    ElFooter,
    ElLink,
    ElRadio,
    ElRadioGroup,
    ElRadioButton,
    ElForm,
    ElFormItem,
    ElTable,
    ElTableColumn,
    ElCard,
    ElInput,
    ElAutocomplete,
    ElSelect,
    ElCascader,
    ElCascaderPanel,
    ElCheckbox,
    ElCheckboxGroup,
    ElCheckboxButton,
    ElBadge,
    ElBreadcrumb,
    ElCarousel,
    ElCarouselItem,
    ElCollapse,
    ElCollapseItem,
    ElColorPicker,
    ElImage,
    ElEmpty,
    ElDropdown,
    ElDropdownMenuItem,
    ElDrawer,
    ElDivider,
    ElDialog,
    ElDescriptions,
    ElDatepicker,
    ElDatetimePicker,
    ElMenu,
    ElMenuItem,
    ElPageHeader,
    ElPagination,
    ElPopconfirm,
    ElPopover,
    ElProgress,
    ElRate,
    ElResult,
    ElSkeleton,
    ElSkeletonItem,
    ElSlider,
    ElStatistic,
    ElStep,
    ElSteps,
    ElSubmenu,
    ElSwitch,
    ElTabPane,
    ElTabs,
    ElTag,
    ElTimeline,
    ElTimelineItem,
    ElTimePicker,
    ElTimeSelect,
    ElTooltip,
    ElTransfer,
    ElTree,
    ElUpload,
    ElAvatar,
    ElBacktop,
  ]
  const icons = [
    'platform-eleme',
    'eleme',
    'delete-solid',
    'delete',
    's-tools',
    'setting',
    'user-solid',
    'user',
    'phone',
    'phone-outline',
    'more',
    'more-outline',
    'star-on',
    'star-off',
    's-goods',
    'goods',
    'warning',
    'warning-outline',
    'question',
    'info',
    'remove',
    'circle-plus',
    'success',
    'error',
    'zoom-in',
    'zoom-out',
    'remove-outline',
    'circle-plus-outline',
    'circle-check',
    'circle-close',
    's-help',
    'help',
    'minus',
    'plus',
    'check',
    'close',
    'picture',
    'picture-outline',
    'picture-outline-round',
    'upload',
    'upload2',
    'download',
    'camera-solid',
    'camera',
    'video-camera-solid',
    'video-camera',
    'message-solid',
    'bell',
    's-cooperation',
    's-order',
    's-platform',
    's-fold',
    's-unfold',
    's-operation',
    's-promotion',
    's-home',
    's-release',
    's-ticket',
    's-management',
    's-open',
    's-shop',
    's-marketing',
    's-flag',
    's-comment',
    's-finance',
    's-claim',
    's-custom',
    's-opportunity',
    's-data',
    's-check',
    's-grid',
    'menu',
    'share',
    'd-caret',
    'caret-left',
    'caret-right',
    'caret-bottom',
    'caret-top',
    'bottom-left',
    'bottom-right',
    'back',
    'right',
    'bottom',
    'top',
    'top-left',
    'top-right',
    'arrow-left',
    'arrow-right',
    'arrow-down',
    'arrow-up',
    'd-arrow-left',
    'd-arrow-right',
    'video-pause',
    'video-play',
    'refresh',
    'refresh-right',
    'refresh-left',
    'finished',
    'sort',
    'sort-up',
    'sort-down',
    'rank',
    'loading',
    'view',
    'c-scale-to-original',
    'date',
    'edit',
    'edit-outline',
    'folder',
    'folder-opened',
    'folder-add',
    'folder-remove',
    'folder-delete',
    'folder-checked',
    'tickets',
    'document-remove',
    'document-delete',
    'document-copy',
    'document-checked',
    'document',
    'document-add',
    'printer',
    'paperclip',
    'takeaway-box',
    'search',
    'monitor',
    'attract',
    'mobile',
    'scissors',
    'umbrella',
    'headset',
    'brush',
    'mouse',
    'coordinate',
    'magic-stick',
    'reading',
    'data-line',
    'data-board',
    'pie-chart',
    'data-analysis',
    'collection-tag',
    'film',
    'suitcase',
    'suitcase-1',
    'receiving',
    'collection',
    'files',
    'notebook-1',
    'notebook-2',
    'toilet-paper',
    'office-building',
    'school',
    'table-lamp',
    'house',
    'no-smoking',
    'smoking',
    'shopping-cart-full',
    'shopping-cart-1',
    'shopping-cart-2',
    'shopping-bag-1',
    'shopping-bag-2',
    'sold-out',
    'sell',
    'present',
    'box',
    'bank-card',
    'money',
    'coin',
    'wallet',
    'discount',
    'price-tag',
    'news',
    'guide',
    'male',
    'female',
    'thumb',
    'cpu',
    'link',
    'connection',
    'open',
    'turn-off',
    'set-up',
    'chat-round',
    'chat-line-round',
    'chat-square',
    'chat-dot-round',
    'chat-dot-square',
    'chat-line-square',
    'message',
    'postcard',
    'position',
    'turn-off-microphone',
    'microphone',
    'close-notification',
    'bangzhu',
    'time',
    'odometer',
    'crop',
    'aim',
    'switch-button',
    'full-screen',
    'copy-document',
    'mic',
    'stopwatch',
    'medal-1',
    'medal',
    'trophy',
    'trophy-1',
    'first-aid-kit',
    'discover',
    'place',
    'location',
    'location-outline',
    'location-information',
    'add-location',
    'delete-location',
    'map-location',
    'alarm-clock',
    'timer',
    'watch-1',
    'watch',
    'lock',
    'unlock',
    'key',
    'service',
    'mobile-phone',
    'bicycle',
    'truck',
    'ship',
    'basketball',
    'football',
    'soccer',
    'baseball',
    'wind-power',
    'light-rain',
    'lightning',
    'heavy-rain',
    'sunrise',
    'sunrise-1',
    'sunset',
    'sunny',
    'cloudy',
    'partly-cloudy',
    'cloudy-and-sunny',
    'moon',
    'moon-night',
    'dish',
    'dish-1',
    'food',
    'chicken',
    'fork-spoon',
    'knife-fork',
    'burger',
    'tableware',
    'sugar',
    'dessert',
    'ice-cream',
    'hot-water',
    'water-cup',
    'coffee-cup',
    'cold-drink',
    'goblet',
    'goblet-full',
    'goblet-square',
    'goblet-square-full',
    'refrigerator',
    'grape',
    'watermelon',
    'cherry',
    'apple',
    'pear',
    'orange',
    'coffee',
    'ice-tea',
    'ice-drink',
    'milk-tea',
    'potato-strips',
    'lollipop',
    'ice-cream-square',
    'ice-cream-round',
  ]

  return propsReducer(map, { prefix: 'el-icon', type: 'elementUi', icons }, extensionContext)
}

export function elementUi2Components() {
  const map = [
    ['el-row', '布局'],
    ['el-col', '布局'],
    ['el-container', '布局容器'],
    ['el-header', '顶栏容器'],
    ['el-aside', '侧边栏容器'],
    ['el-main', '主要区域容器'],
    ['el-footer', '底栏容器'],
    ['el-button', '按钮'],
    ['el-link', '文字链接'],
    ['el-radio', '单选框'],
    ['el-radio-group', '单选框组'],
    ['el-radio-button', '按钮样式的单选组合'],
    ['el-checkbox', '多选框'],
    ['el-checkbox-group', '多选框组'],
    ['el-checkbox-button', '按钮样式的多选组合'],
    ['el-input', '输入框'],
    ['el-input-number', '计数器'],
    ['el-select', '选择器'],
    ['el-option', '基础多选'],
    ['el-option-group', '备选项进行分组展示'],
    ['el-cascader', '级联选择器'],
    ['el-cascader-panel', '级联面板'],
    ['el-switch', '开关'],
    ['el-slider', '滑块'],
    ['el-time-select', '时间选择器'],
    ['el-date-picker', '日期选择器/日期时间选择器'],
    ['el-upload', '上传'],
    ['el-rate', '评分'],
    ['el-color-picker', '颜色选择器'],
    ['el-transfer', '穿梭框'],
    ['el-form', '表单'],
    ['el-form-item', '表单项'],
    ['el-table', '表格'],
    ['el-table-column', '表格项'],
    ['el-tag', '标签'],
    ['el-progress', '进度条'],
    ['el-tree', '树形控件'],
    ['el-pagination', '分页'],
    ['el-badge', '标记'],
    ['el-avatar', '头像'],
    ['el-skeleton', '骨架屏'],
    ['el-empty', '空状态'],
    ['el-descriptions', '描述列表'],
    ['el-descriptions-item', '描述列表项'],
    ['el-result', '结果'],
    ['el-statistic', '统计数值'],
    ['el-alert', '警告'],
    ['el-menu', '导航菜单'],
    ['el-submenu', '导航子菜单'],
    ['el-menu-item', '导航菜单项'],
    ['el-tabs', '标签页'],
    ['el-tab-pane', '标签项'],
    ['el-breadcrumb', '面包屑'],
    ['el-breadcrumb-item', '面包屑项'],
    ['el-page-header', '页头'],
    ['el-dropdown', '下拉菜单'],
    ['el-dropdown-menu', '下拉菜单列表'],
    ['el-dropdown-item', '下拉菜单列表项'],
    ['el-steps', '步骤条'],
    ['el-dialog', '对话框'],
    ['el-tooltip', '文字提示'],
    ['el-popover', '弹出框'],
    ['el-popconfirm', '气泡确认框'],
    ['el-card', '卡片'],
    ['el-carousel', '走马灯'],
    ['el-carousel-item', '走马灯项'],
    ['el-collapse', '折叠面板'],
    ['el-collapse-item', '折叠面板项'],
    ['el-timeline', '时间线'],
    ['el-timeline-item', '时间线项'],
    ['el-divider', '分割线'],
    ['el-calendar', '日历'],
    ['el-image', '图片'],
    ['el-backtop', '回到顶部'],
    ['el-drawer', '抽屉'],
    ['el-autocomplete', '远程搜索'],
  ]
  return componentsReducer(map)
}
