export const UINames = [
  'element-ui',
  'element-plus',
  'antd',
  'ant-design-vue',
  '@varlet/ui',
  'vant',
  'naive-ui',
  'vuetify',
  '@chakra-ui/react',
  '@chakra-ui/vue',
  '@skeletonlabs/skeleton',
  'primevue',
  'quasar',
  '@nextui-org/react',
  '@nuxt/ui',
  'shadcn-vue',
  'radix-vue',
  '@arco-design/web-react',
  '@arco-design/web-vue',
  'uview-ui',
  '@tarojs/components',
  '@nuxt/ui-pro',
  'antd-mobile',
  'uview-plus',
  'bits-ui',
  '@mui/material',
  'shadcn-ui',
  '@opentiny/vue',
  '@nutui/nutui',
  'view-ui-plus',
  'wot-design-uni',
  '@ark-ui/vue',
]

export const nameMap: any = {
  '@varlet/ui': 'varlet',
  '@chakraUi/react': 'chakraUiReact',
  '@chakraUi/vue': 'chakraUiVue',
  '@skeletonlabs/skeleton': 'skeleton',
  '@nextuiOrg/react': 'nextui',
  '@nuxt/ui': 'nuxtui',
  '@arcoDesign/webReact': 'arcoDesign',
  '@arcoDesign/webVue': 'arcoDesignVue',
  'uviewUi': 'uview',
  '@tarojs/components': 'taro',
  '@nuxt/uiPro': 'nuxtUiPro',
  'bits-ui': 'shadcnSvelte',
  '@mui/material': 'materialUi',
  '@opentiny/vue': 'tinyVue',
  '@nutui/nutui': 'nutUi',
  '@arkUi/vue': 'arkVue',
}
